### ISSUE TITLE
Further plan for revising the source code of the paper

### ISSUE THREAD

**Issue by mo666666** [Robin-WZQ/T2IShield#2]
Hi, Zhongqi! Thank you for this interesting work. Do you have a plan for releasing the source code of the paper? 

Look forward to your reply.

**Comment by Robin-WZQ** [comment]
Hi! @mo666666,
Sorry for replying late. We promise to release our data and testing/training code of detection, localization and mitigation before 2024/9/15.
Thanks.

**Comment by mo666666** [comment]
Zhongqi, thank you for your reply. The revision plan is OK for me.
